-- MySQL Script generated by MySQL Workbench
-- Sun Aug 29 12:35:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbmarcolegal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbmarcolegal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbmarcolegal` DEFAULT CHARACTER SET utf8 ;
USE `dbmarcolegal` ;

-- -----------------------------------------------------
-- Table `dbmarcolegal`.`LEY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbmarcolegal`.`LEY` (
  `idley` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idley`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbmarcolegal`.`TITULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbmarcolegal`.`TITULO` (
  `idtitulo` INT NOT NULL AUTO_INCREMENT,
  `idley` INT NOT NULL,
  `descripcion` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idtitulo`),
  INDEX `fk_ley_titulo_idx` (`idley` ASC),
  CONSTRAINT `fk_ley_titulo`
    FOREIGN KEY (`idley`)
    REFERENCES `dbmarcolegal`.`LEY` (`idley`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbmarcolegal`.`ROL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbmarcolegal`.`ROL` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbmarcolegal`.`PERMISO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbmarcolegal`.`PERMISO` (
  `idpermiso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpermiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbmarcolegal`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbmarcolegal`.`USUARIO` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `idrol` INT NOT NULL,
  `nombre` VARCHAR(60) NOT NULL,
  `apellido` VARCHAR(60) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `login` VARCHAR(20) NOT NULL,
  `clave` VARCHAR(64) NOT NULL,
  `condicion` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  INDEX `fk_usuario_cargo_idx` (`idrol` ASC),
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`idrol`)
    REFERENCES `dbmarcolegal`.`ROL` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbmarcolegal`.`CAPITULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbmarcolegal`.`CAPITULO` (
  `idcapitulo` INT NOT NULL AUTO_INCREMENT,
  `idley` INT NOT NULL,
  `idtitulo` INT NOT NULL,
  `descripcion` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idcapitulo`),
  INDEX `fk_capitulo_titulo_idx` (`idley` ASC, `idtitulo` ASC),
  CONSTRAINT `fk_capitulo_titulo`
    FOREIGN KEY (`idley` , `idtitulo`)
    REFERENCES `dbmarcolegal`.`TITULO` (`idley` , `idtitulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbmarcolegal`.`ARTICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbmarcolegal`.`ARTICULO` (
  `idarticulo` INT NOT NULL AUTO_INCREMENT,
  `idley` INT NOT NULL,
  `idtitulo` INT NOT NULL,
  `idcapitulo` INT NOT NULL,
  `numero` INT NOT NULL,
  `nombre` VARCHAR(60) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idarticulo`),
  INDEX `fk_articulo_capitulo_idx` (`idley` ASC, `idtitulo` ASC, `idcapitulo` ASC),
  CONSTRAINT `fk_articulo_capitulo`
    FOREIGN KEY (`idley` , `idtitulo` , `idcapitulo`)
    REFERENCES `dbmarcolegal`.`CAPITULO` (`idley` , `idtitulo` , `idcapitulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbmarcolegal`.`INSTITUCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbmarcolegal`.`INSTITUCION` (
  `idinstitucion` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idinstitucion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbmarcolegal`.`EVALUACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbmarcolegal`.`EVALUACION` (
  `idevaluacion` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NULL,
  `idley` INT NOT NULL,
  `idtitulo` INT NOT NULL,
  `idcapitulo` INT NOT NULL,
  `idarticulo` INT NOT NULL,
  `idinstitucion` INT NOT NULL,
  `marca` TINYINT NULL,
  `observacion` VARCHAR(300) NULL,
  `nombredocumento1` VARCHAR(60) NULL,
  `nombredocumento2` VARCHAR(60) NULL,
  `nombredocumento3` VARCHAR(60) NULL,
  PRIMARY KEY (`idevaluacion`),
  INDEX `fk_evaluacion_usuario_idx` (`idusuario` ASC),
  INDEX `fk_evaluacion_ley_idx` (`idley` ASC),
  INDEX `fk_evaluacion_titulo_idx` (`idtitulo` ASC),
  INDEX `fk_evaluacion_capitulo_idx` (`idcapitulo` ASC),
  INDEX `fk_evaluacion_artuculo_idx` (`idarticulo` ASC),
  INDEX `fk_evaluacion_institucion_idx` (`idinstitucion` ASC),
  CONSTRAINT `fk_evaluacion_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `dbmarcolegal`.`USUARIO` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluacion_ley`
    FOREIGN KEY (`idley`)
    REFERENCES `dbmarcolegal`.`LEY` (`idley`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluacion_titulo`
    FOREIGN KEY (`idtitulo`)
    REFERENCES `dbmarcolegal`.`TITULO` (`idtitulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluacion_capitulo`
    FOREIGN KEY (`idcapitulo`)
    REFERENCES `dbmarcolegal`.`CAPITULO` (`idcapitulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluacion_artuculo`
    FOREIGN KEY (`idarticulo`)
    REFERENCES `dbmarcolegal`.`ARTICULO` (`idarticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluacion_institucion`
    FOREIGN KEY (`idinstitucion`)
    REFERENCES `dbmarcolegal`.`INSTITUCION` (`idinstitucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbmarcolegal`.`PERMISO_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbmarcolegal`.`PERMISO_USUARIO` (
  `idpermiso_usuario` INT NOT NULL AUTO_INCREMENT,
  `idpermiso_fk` INT NOT NULL,
  `idusuario_fk` INT NOT NULL,
  PRIMARY KEY (`idpermiso_usuario`),
  INDEX `fk_permisousuario_permiso_idx` (`idpermiso_fk` ASC),
  INDEX `fk_permisousuario_usuario_idx` (`idusuario_fk` ASC),
  CONSTRAINT `fk_permisousuario_permiso`
    FOREIGN KEY (`idpermiso_fk`)
    REFERENCES `dbmarcolegal`.`PERMISO` (`idpermiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permisousuario_usuario`
    FOREIGN KEY (`idusuario_fk`)
    REFERENCES `dbmarcolegal`.`USUARIO` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
